version: '3.5'
services:
    scheduler:
        container_name: scheduler-ofelia
        image: mcuadros/ofelia:latest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./config.ini:/etc/ofelia/config.ini
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro  
networks: 
  default: 
    name: idea 
    external: true
